### ISSUE TITLE
Unable to create a package

### ISSUE THREAD

**Issue by scramatte** [c-cast/nova-packager#1]
Hi,

I've got exception creating package 

```
ErrorException 

  file_get_contents(/opt/eom/vendor/c-cast/nova-packager/src/Commands/../../Stubs/ApiRoutes.stub): Failed to open stream: No such file or directory

```

![image](https://user-images.githubusercontent.com/188766/205500461-8a1cd033-1035-4d79-93ea-1164a9b79230.png)

Any idea of what occurs here?

**Comment by mycmdev** [comment]
Seems like you can't reach the directory during the file_get_contents function. 
Have you tried with a plain php project to use **file_get_contents** function?

**Comment by scramatte** [comment]
Finally, I've switched to another package that cover whole Laravel Modules not just Nova ones.  
https://docs.laravelmodules.com/v9/language

I'll probably going to port nova missing commands to the above package.

Regards
